using UnityEngine;

public class PlayerController : MonoBehaviour
{
    public float moveSpeed = 5f;
    public float jumpForce = 3f;
    private Rigidbody2D rb;
    private float moveInput;
    public AudioSource audioSource;
    public AudioClip energySound;
    public AudioClip hitSound;
    public AudioClip ExitSound;
    

    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        audioSource = GetComponent<AudioSource>();
    }

    void Update()
    {
        // Ø­Ø±Ú©Øª Ú†Ù¾ Ùˆ Ø±Ø§Ø³Øª
        moveInput = Input.GetAxis("Horizontal");
        rb.velocity = new Vector2(moveInput * moveSpeed, rb.velocity.y);

        // Ù¾Ø±Ø´ Ø¨Ø§ Space
        if (Input.GetKeyDown(KeyCode.Space) && Mathf.Abs(rb.velocity.y) < 0.01f)
        {
            rb.velocity = new Vector2(rb.velocity.x, jumpForce);
        }
    }

    public void IncreaseJump(float amount)
    {
        jumpForce += amount;

        // ÙˆÙ‚ØªÛŒ Ù…Ù‚Ø¯Ø§Ø± Ù¾Ø±Ø´ Ø¨Ù‡ Û±Û² Ø±Ø³ÛŒØ¯ØŒ Ú†Ø±Ø®Ø´ Ø§Ø´ÛŒØ§ ÙØ¹Ø§Ù„ Ø´ÙˆØ¯
        if (jumpForce >= 12f)
        {
            StartRotatingObjects();
        }
    }

    private void StartRotatingObjects()
    {
        GameObject[] rotatingObjects = GameObject.FindGameObjectsWithTag("Rotating"); // Ù¾ÛŒØ¯Ø§ Ú©Ø±Ø¯Ù† Ø§Ø´ÛŒØ§ Ø¨Ø§ ØªÚ¯ "Rotating"
        foreach (GameObject obj in rotatingObjects)
        {
            obj.GetComponent<RotateObject>().StartRotation(); // ÙØ¹Ø§Ù„â€ŒØ³Ø§Ø²ÛŒ Ú†Ø±Ø®Ø´
        }
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        Debug.Log("Ø¨Ø§Ø²ÛŒÚ©Ù† ÙˆØ§Ø±Ø¯ Ù…Ø­Ø¯ÙˆØ¯Ù‡ Ø§Ù†Ø±Ú˜ÛŒ Ø´Ø¯!"); // Ø¨Ø±Ø±Ø³ÛŒ Ø¨Ø±Ø®ÙˆØ±Ø¯
        if (other.CompareTag("Energy"))
        {
            IncreaseJump(3f);
            Destroy(other.gameObject);
        }

        if (other.CompareTag("Energy"))
        {
            audioSource.PlayOneShot(energySound); // Ù¾Ø®Ø´ ØµØ¯Ø§ÛŒ Ø¬Ù…Ø¹â€ŒØ¢ÙˆØ±ÛŒ Ø§Ù†Ø±Ú˜ÛŒ
            Destroy(other.gameObject);
        }

        if (other.CompareTag("ENEMY"))
        {
            audioSource.PlayOneShot(hitSound); // Ù¾Ø®Ø´ ØµØ¯Ø§ÛŒ Ø¨Ø±Ø®ÙˆØ±Ø¯ Ø¨Ø§ Ø¯Ø´Ù…Ù†
            Destroy(other.gameObject);
        }


        if (other.CompareTag("by")) // Ù¾Ø®Ø´ ØµØ¯Ø§ÛŒ Ø¬Ø§ÛŒØ²Ù‡ ğŸ¯
        {
            audioSource.PlayOneShot(ExitSound); // Ù¾Ø®Ø´ ØµØ¯Ø§ÛŒ Ø¯Ø±ÛŒØ§ÙØª Ø¬Ø§ÛŒØ²Ù‡
            Destroy(other.gameObject);
        }
    }

}
